// <auto-generated />
using System;
using ConectaAtende.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConectaAtende.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221181549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConectaAtende.Domain.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Idade = 30,
                            Nome = "Carlos"
                        });
                });

            modelBuilder.Entity("ConectaAtende.Domain.Entidades.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataAtualizacao = new DateTime(2026, 2, 21, 18, 15, 49, 255, DateTimeKind.Utc).AddTicks(4298),
                            DataCriacao = new DateTime(2026, 2, 21, 18, 15, 49, 255, DateTimeKind.Utc).AddTicks(4296),
                            Nome = "João Silva",
                            Numero = "11999999999"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DataAtualizacao = new DateTime(2026, 2, 21, 18, 15, 49, 255, DateTimeKind.Utc).AddTicks(4300),
                            DataCriacao = new DateTime(2026, 2, 21, 18, 15, 49, 255, DateTimeKind.Utc).AddTicks(4300),
                            Nome = "Maria Souza",
                            Numero = "11888888888"
                        });
                });

            modelBuilder.Entity("ConectaAtende.Domain.Entidades.ContatoRecente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("ContatosRecentes");
                });

            modelBuilder.Entity("ConectaAtende.Domain.Entidades.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ContatoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataCriacao = new DateTime(2026, 2, 21, 18, 15, 49, 255, DateTimeKind.Utc).AddTicks(4450),
                            Prioridade = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ConectaAtende.Domain.Entidades.ContatoRecente", b =>
                {
                    b.HasOne("ConectaAtende.Domain.Entidades.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");
                });
#pragma warning restore 612, 618
        }
    }
}
